// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCB77pfBx4anRWrqi9xxUafVY7rImT9mk',
    appId: '1:756313885268:web:3742768afc1e6bed373bc1',
    messagingSenderId: '756313885268',
    projectId: 'crud-firebase-eb72b',
    authDomain: 'crud-firebase-eb72b.firebaseapp.com',
    storageBucket: 'crud-firebase-eb72b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8oNGqcxqrj8VAmG0HamcsXg3hcFEX9U',
    appId: '1:756313885268:android:ba3dd02690d04332373bc1',
    messagingSenderId: '756313885268',
    projectId: 'crud-firebase-eb72b',
    storageBucket: 'crud-firebase-eb72b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12f8uIjF3rY5XwKI8vJJ_WPxM-2JmPns',
    appId: '1:756313885268:ios:59c905d1dd2c5273373bc1',
    messagingSenderId: '756313885268',
    projectId: 'crud-firebase-eb72b',
    storageBucket: 'crud-firebase-eb72b.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
